service_controller:
    resource: 'routes/service.yaml'

admin_controller:
    resource: 'routes/admin.yaml'

user_controller:
    resource: 'routes/user.yaml'

register_controller:
    resource: 'routes/register.yaml'

login_controller:
    resource: 'routes/login.yaml'


