index:
    path: /
    controller: App\Controller\ServiceController::indexAction

results:
    path: /results
    controller: App\Controller\ServiceController::resultsAction

admin:
    path: /admin
    controller: App\Controller\AdminController::indexAction

checkUsernameAvaibility:
    path: /checkUsernameAvaibility
    controller: App\Controller\RegisterController::checkUsernameAvaibility

register:
    path: /register
    controller: App\Controller\RegisterController::indexAction

addUserToDB:
    path: /registerUser
    controller: App\Controller\RegisterController::registerUserAction

login:
    path: /login
    controller: App\Controller\LoginController::loginAction

sendRegisterMail:
    path: /sendRegisterMail
    controller: App\Controller\RegisterController:sendRegisterMailAction

activationLink:
    path: /activateUser/{username}/{time}
    controller: App\Controller\RegisterController:activateUserAction