index:
    path: /
    controller: App\Controller\ServiceController::indexAction

results:
    path: /results
    controller: App\Controller\ServiceController::resultsAction

admin:
    path: /admin
    controller: App\Controller\AdminController::indexAction

checkUsernameAvaibility:
    path: /checkUsernameAvaibility
    controller: App\Controller\RegisterController::checkUsernameAvaibilityAction

register:
    path: /register
    controller: App\Controller\RegisterController::indexAction

addUserToDB:
    path: /registerUser
    controller: App\Controller\RegisterController::registerUserAction

loginForm:
    path: /login
    controller: App\Controller\LoginController::indexAction

loginUser:
    path: /loginUser
    controller: App\Controller\LoginController:loginAction

logoutUser:
    path: /logoutUser
    controller: App\Controller\LoginController:logoutAction

sendRegisterMail:
    path: /sendRegisterMail
    controller: App\Controller\RegisterController:sendRegisterMailAction

activationLink:
    path: /activateUser/{username}/{time}
    controller: App\Controller\RegisterController:activateUserAction

resetPassword:
    path: /resetPassword
    controller: App\Controller\LoginController:resetPasswordAction

addTask:
    path: /addTask
    controller: App\Controller\AdminController:addTaskAction

query:
    path: /query
    controller: App\Controller\AdminController:queryAction