index:
    path: /
    controller: App\Controller\ServiceController::indexAction

results:
    path: /results
    controller: App\Controller\ServiceController::resultsAction

admin:
    path: /admin
    controller: App\Controller\AdminPanelController::indexAction

register:
    path: /register
    controller: App\Controller\RegisterController::indexAction

registerUser:
    path: /registeruser
    controller: App\Controller\RegisterController::registerUserAction