index:
    path: /
    controller: App\Controller\ServiceController::indexAction

results:
    path: /results
    controller: App\Controller\ServiceController::resultsAction

admin:
    path: /admin
    controller: App\Controller\AdminPanelController::indexAction

checkUsernameAvaibility:
    path: /checkUsernameAvaibility
    controller: App\Controller\RegisterController::checkUsernameAvaibility

register:
    path: /register
    controller: App\Controller\RegisterController::indexAction

registerUser:
    path: /registerUser
    controller: App\Controller\RegisterController::registerUserAction