index:
    path: /
    host:     "localhost"
    controller: App\Controller\ServiceController::indexAction

results:
    path: /results
    controller: App\Controller\ServiceController::resultsAction

admin:
    path: /admin
    host:     "localhost"
    controller: App\Controller\AdminController::indexAction

panel:
    path: /panel
    controller: App\Controller\UserController::indexAction

checkUsernameAvaibility:
    path: /checkUsernameAvaibility
    controller: App\Controller\RegisterController::checkUsernameAvaibilityAction

register:
    path: /register
    controller: App\Controller\RegisterController::indexAction

addUserToDB:
    path: /registerUser
    controller: App\Controller\RegisterController::registerUserAction

loginForm:
    path: /login
    controller: App\Controller\LoginController::indexAction

loginUser:
    path: /loginUser
    controller: App\Controller\LoginController::loginAction

logoutUser:
    path: /logoutUser
    controller: App\Controller\LoginController::logoutAction

sendRegisterMail:
    path: /sendRegisterMail
    controller: App\Controller\RegisterController::sendRegisterMailAction

activationLink:
    path: /activateUser/{username}/{time}
    controller: App\Controller\RegisterController::activateUserAction

resetPassword:
    path: /resetPassword
    controller: App\Controller\LoginController::resetPasswordAction

addTask:
    path: /addTask
    controller: App\Controller\UserController::addTaskAction

searchJobs:
    path: /searchJobs/{lang}
    controller: App\Controller\UserController::searchJobsAction

searchCountries:
    path: /searchCountries/{lang}
    controller: App\Controller\UserController::searchCountriesAction

addNewJobName:
    path: /addNewJobName
    controller: App\Controller\AdminController::addNewJobNameAction

addNewCountryName:
    path: /addNewCountryName
    controller: App\Controller\AdminController::addNewCountryNameAction

searchAreaInCountry:
    path: /searchAreaInCountry
    controller: App\Controller\UserController::searchAreaInCountryAction

addNewAreaName:
    path: /addNewAreaName
    controller: App\Controller\AdminController::addNewAreaNameAction

addJobEnName:
    path: /addJobEnName
    controller: App\Controller\AdminController:addJobEnNameAction

addJobFrName:
    path: /addJobFrName
    controller: App\Controller\AdminController:addJobFrNameAction

activateTask:
    path: /activateTask/{id}/{userId}
    controller: App\Controller\AdminController::activateTaskAction

deactivateTask:
    path: /deactivateTask/{id}/{userId}
    controller: App\Controller\AdminController:deactivateTaskAction

addUserLangs:
    path: /addUserLangs
    controller: App\Controller\UserController::addUserLangsAction

userDetails:
    path: /admin/user/{id}
    controller: App\Controller\AdminController:userDetailsAction
