swiftmailer:
  spool:     { type: memory }
  transport: smtp
  host:      smtp.mailtrap.io
  username:  5a508109a13a44
  password:  6396145cec1544
  auth_mode: cram-md5
  port: 2525

#sqwndjzdjsxofmmf
